name: MAPP - Mobile App Review Crawler & Deploy

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write 

jobs:
  crawl:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Environment
        run: |
          echo "🔍 Debugging self-hosted runner environment..."
          echo "PWD: $(pwd)"
          echo "USER: $(whoami)"
          echo "Python path: $(which python)"
          echo "Python version: $(python --version)"
          echo "Pip path: $(which pip)"
          ls -la
          
      - name: Simple Install Dependencies
        run: |
          echo "📦 Installing dependencies with system Python..."
          python -m pip install --user --upgrade pip
          python -m pip install --user -r requirements.txt
      - name: Environment Check
        run: |
          echo "📦 Checking installed packages..."
          python -m pip list --user | grep -E "(google|play|scraper)" || echo "No matching packages"

      - name: Run MAPP Crawler with Debug
        run: |
          echo "🚀 Starting MAPP Crawler with enhanced debugging..."
          echo "📊 Configuration:"
          echo "   • REVIEW_COUNT: ${REVIEW_COUNT}"
          echo "   • ANALYSIS_DAYS: ${ANALYSIS_DAYS}"
          python -u main.py
        env:
          PYTHONUNBUFFERED: 1
          DEBUG_MODE: 1
          REVIEW_COUNT: 500
          ANALYSIS_DAYS: 7

      - name: Rename HTML file to index.html
        run: |
          cd ./output
          cp mapp_report_*.html index.html
          echo "✓ index.html created from MAPP report"
          ls -la *.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./output

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4