name: MAPP - Mobile App Review Crawler & Deploy

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write 

jobs:
  crawl-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-nanum
      
      - name: Verify fonts
        run: fc-list :lang=ko

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run MAPP Crawler
        run: |
          python mapp-review-crawl.py

      - name: Rename HTML file to index.html
        run: |
          cd ./output
          cp mapp_report_*.html index.html
          echo "✓ index.html created from MAPP report"
          ls -la *.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./output

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4