name: MAPP - Mobile App Review Crawler & Deploy

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write 

jobs:
  crawl:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check macOS environment
        run: |
          echo "Running on macOS self-hosted runner"
          echo "Current location: $(curl -s https://ipapi.co/city/), $(curl -s https://ipapi.co/country_name/)"
          echo "Python version: $(python3 --version)"
          echo "Pip version: $(pip3 --version)"

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Environment Check
        run: |
          echo "📦 Installed packages:"
          pip list | grep -E "(google|play|scraper)" || echo "No matching packages"

      - name: Run MAPP Crawler with Debug
        run: |
          echo "🚀 Starting MAPP Crawler with enhanced debugging..."
          echo "📊 Configuration:"
          echo "   • REVIEW_COUNT: ${REVIEW_COUNT}"
          echo "   • ANALYSIS_DAYS: ${ANALYSIS_DAYS}"
          python3 -u main.py
        env:
          PYTHONUNBUFFERED: 1
          DEBUG_MODE: 1
          REVIEW_COUNT: 500
          ANALYSIS_DAYS: 7

      - name: Rename HTML file to index.html
        run: |
          cd ./output
          cp mapp_report_*.html index.html
          echo "✓ index.html created from MAPP report"
          ls -la *.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./output

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4